version: '3.8'

services:
  # Инфраструктура
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - app-network

  # Базы данных для сервисов
  postgres_orders:
    image: postgres:13-alpine
    container_name: postgres_orders
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orders_db
    ports:
      - "5431:5432"
    volumes:
      - postgres_orders_data:/var/lib/postgresql/data
    networks:
      - app-network

  postgres_payments:
    image: postgres:13-alpine
    container_name: postgres_payments
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payments_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_payments_data:/var/lib/postgresql/data
    networks:
      - app-network
      
  postgres_delivery:
    image: postgres:13-alpine
    container_name: postgres_delivery
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=delivery_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_delivery_data:/var/lib/postgresql/data
    networks:
      - app-network

  postgres_notifications:
    image: postgres:13-alpine
    container_name: postgres_notifications
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=notifications_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_notifications_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis_cart:
    image: redis:6-alpine
    container_name: redis_cart
    ports:
      - "6379:6379"
    volumes:
      - redis_cart_data:/data
    networks:
      - app-network

volumes:
  rabbitmq_data:
  postgres_orders_data:
  postgres_payments_data:
  postgres_delivery_data:
  postgres_notifications_data:
  redis_cart_data:

networks:
  app-network:
    driver: bridge